"""ofxaccount account_id

Revision ID: 4b8ce290f890
Revises: 2d295ac0fc07
Create Date: 2016-06-23 08:32:42.429402

"""

# revision identifiers, used by Alembic.
revision = '4b8ce290f890'
down_revision = '2d295ac0fc07'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ofxaccount', sa.Column('account_id', sa.String(length=255), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ofxaccount', 'account_id')
    ### end Alembic commands ###
